#include <dsp/ZeroPhaseFilter.h>
#include <engine/BinaryMatrix.h>

#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include <cmath>
#include <numbers>
#include <vector>

using namespace rvcara;
using Catch::Approx;

namespace
{
    /** The reference high-pass: fifth-order Butterworth at 48 Hz for 16 kHz, as
        second-order sections. Generated by SciPy and printed at full precision; these
        are the same numbers the exporter writes into every manifest.
    */
    std::vector<dsp::BiquadCoefficients> getReferenceHighPass()
    {
        return {
            { 0.9699606451838447, -0.9699606451838447, 0.0, 1.0, -0.9813258904926881, 0.0 },
            { 1.0, -2.0, 1.0, 1.0, -1.9696106864374547, 0.9699606452559844 },
            { 1.0, -2.0, 1.0, 1.0, -1.9880652422382208, 0.9884184800471566 },
        };
    }

    constexpr int referencePadLength = 18;

    std::vector<float> makeSine (double frequencyHz, double sampleRate, int numSamples)
    {
        std::vector<float> signal (static_cast<std::size_t> (numSamples));

        for (int sampleIndex = 0; sampleIndex < numSamples; ++sampleIndex)
            signal[static_cast<std::size_t> (sampleIndex)] =
                static_cast<float> (std::sin (2.0 * std::numbers::pi * frequencyHz
                                              * static_cast<double> (sampleIndex) / sampleRate));

        return signal;
    }

    double measureRootMeanSquare (const std::vector<float>& signal, int firstSample, int lastSample)
    {
        double sumOfSquares = 0.0;

        for (int sampleIndex = firstSample; sampleIndex < lastSample; ++sampleIndex)
            sumOfSquares += static_cast<double> (signal[static_cast<std::size_t> (sampleIndex)])
                          * static_cast<double> (signal[static_cast<std::size_t> (sampleIndex)]);

        return std::sqrt (sumOfSquares / static_cast<double> (lastSample - firstSample));
    }
} // namespace

TEST_CASE ("an empty cascade is a no-op", "[filter]")
{
    const dsp::ZeroPhaseFilter filter;
    CHECK (filter.isEmpty());

    std::vector<float> signal { 1.0f, 2.0f, 3.0f, 4.0f };
    filter.process (signal.data(), static_cast<int> (signal.size()));

    CHECK (signal == std::vector<float> { 1.0f, 2.0f, 3.0f, 4.0f });
}

TEST_CASE ("the high-pass removes content below its corner and passes content above", "[filter]")
{
    const dsp::ZeroPhaseFilter filter { getReferenceHighPass(), referencePadLength };

    constexpr auto sampleRate = 16000.0;
    constexpr auto numSamples = 8000;

    SECTION ("25 Hz is heavily attenuated")
    {
        auto signal = makeSine (25.0, sampleRate, numSamples);
        const auto before = measureRootMeanSquare (signal, 1000, numSamples - 1000);

        filter.process (signal.data(), numSamples);
        const auto after = measureRootMeanSquare (signal, 1000, numSamples - 1000);

        // Forward-backward filtering squares the magnitude response, so a fifth-order
        // design attenuates far harder than its nominal 30 dB/octave here.
        CHECK (after < before * 0.02);
    }

    SECTION ("440 Hz passes essentially untouched")
    {
        auto signal = makeSine (440.0, sampleRate, numSamples);
        const auto before = measureRootMeanSquare (signal, 1000, numSamples - 1000);

        filter.process (signal.data(), numSamples);
        const auto after = measureRootMeanSquare (signal, 1000, numSamples - 1000);

        CHECK (after == Approx (before).epsilon (0.001));
    }

    SECTION ("a constant offset is removed")
    {
        std::vector<float> signal (numSamples, 0.5f);
        filter.process (signal.data(), numSamples);

        CHECK (std::abs (signal[numSamples / 2]) < 1.0e-4f);
    }
}

TEST_CASE ("the filter is zero phase", "[filter]")
{
    // The reason this filter is run forwards and backwards at all. A causal filter
    // delays its output; a zero-phase one does not, so a symmetric input must produce a
    // symmetric output. Any group delay would break that symmetry.
    const dsp::ZeroPhaseFilter filter { getReferenceHighPass(), referencePadLength };

    constexpr auto numSamples = 4001;
    std::vector<float> signal (numSamples, 0.0f);

    // A symmetric raised-cosine burst centred in the buffer.
    constexpr auto burstHalfWidth = 400;
    const auto centre = numSamples / 2;

    for (int offset = -burstHalfWidth; offset <= burstHalfWidth; ++offset)
    {
        const auto window = 0.5 - 0.5 * std::cos (std::numbers::pi
                                                  * (static_cast<double> (offset + burstHalfWidth)
                                                     / static_cast<double> (burstHalfWidth)));
        signal[static_cast<std::size_t> (centre + offset)] = static_cast<float> (window);
    }

    filter.process (signal.data(), numSamples);

    auto worstAsymmetry = 0.0f;

    for (int offset = 1; offset < centre - 1; ++offset)
        worstAsymmetry = std::max (worstAsymmetry,
                                   std::abs (signal[static_cast<std::size_t> (centre + offset)]
                                             - signal[static_cast<std::size_t> (centre - offset)]));

    CHECK (worstAsymmetry < 1.0e-5f);
}

TEST_CASE ("the high-pass matches SciPy's filtfilt", "[filter]")
{
    // Golden comparison against scipy.signal.filtfilt, which is what the reference
    // pipeline calls. Both initialise each section to the steady state for its first
    // sample, so they agree to within float32 rounding across the whole signal — there is
    // no boundary allowance to make, and if one were needed it would mean the steady-state
    // initialisation in ZeroPhaseFilter had regressed.
    const juce::File fixtures { RVCARA_TEST_FIXTURE_DIR };

    const auto signalFixture = engine::BinaryMatrix::load (fixtures.getChildFile ("test_signal.bin"));
    const auto expected = engine::BinaryMatrix::load (fixtures.getChildFile ("expected_high_pass.bin"));

    REQUIRE (signalFixture.isValid());
    REQUIRE (expected.isValid());

    const auto numSamples = signalFixture.getNumColumns();
    REQUIRE (expected.getNumColumns() == numSamples);

    std::vector<float> signal { signalFixture.getData(), signalFixture.getData() + numSamples };

    const dsp::ZeroPhaseFilter filter { getReferenceHighPass(), referencePadLength };
    filter.process (signal.data(), numSamples);

    auto worstDifference = 0.0f;

    for (int sampleIndex = 0; sampleIndex < numSamples; ++sampleIndex)
        worstDifference = std::max (worstDifference,
                                    std::abs (signal[static_cast<std::size_t> (sampleIndex)]
                                              - expected.getData()[sampleIndex]));

    CHECK (worstDifference < 1.0e-5f);
}
