#pragma once

#include <juce_dsp/juce_dsp.h>

#include <memory>
#include <vector>

namespace rvcara
{

/** The log-mel spectrogram the pitch estimator takes as input.

    This is the one part of the pitch pipeline that stayed in C++ rather than being
    folded into the ONNX graph, so it has to agree with what RMVPE was trained on
    exactly. Four details carry that agreement, and each is a plausible way to get a
    working spectrogram that produces a wrong pitch track:

    - **The window is the periodic Hann**, dividing by @c windowSize rather than
      @c windowSize @c - @c 1. The symmetric form — what `numpy.hanning` returns — is
      wrong here and shifts every mel bin's energy slightly.
    - **Framing is centred.** The signal is reflected by half a transform at each end
      so that frame @c k is centred on sample `k * hopSize`, giving
      `1 + numSamples / hopSize` frames. Without this the pitch track is offset by
      half a window against the content features.
    - **Magnitude, not power.** The filter bank is applied to @c |X|, not @c |X|².
    - **The filter bank is a data file**, generated by librosa at export time on the
      HTK mel scale with Slaney area normalisation, and never recomputed here. It is
      not the same mel scale as the one in PitchConversions.h.

    The output is laid out as ONNX Runtime wants it — `[1, numMelBins, numFrames]`,
    mel bin as the slow axis — so it can be handed to the session without a transpose.
*/
class MelSpectrogram
{
public:
    /** Front-end parameters, all read from the model manifest. */
    struct Configuration
    {
        int fftSize { 1024 };
        int windowSize { 1024 };
        int hopSizeInSamples { 160 };
        int numMelBins { 128 };
        int numBins { 513 };            ///< fftSize / 2 + 1
        float magnitudeFloor { 1.0e-5f }; ///< clamp before the logarithm
        bool isCentred { true };
    };

    /** @param configuration  Front-end parameters.
        @param filterBank     `[numMelBins, numBins]` row-major, from mel_filter_bank.bin.
    */
    MelSpectrogram (const Configuration& configuration, std::vector<float> filterBank);

    /** @returns The number of frames produced for a given input length. */
    [[nodiscard]] int getNumFrames (int numSamples) const noexcept;

    /** Computes the spectrogram.

        @param samples      Mono input at the front end's sample rate.
        @param numSamples   Its length.
        @param destination  Filled with `numMelBins * numFrames` values in
                            `[1, numMelBins, numFrames]` layout; resized as needed.
        @returns            The number of frames written, or zero if the input is too
                            short to reflect-pad.
    */
    int process (const float* samples, int numSamples, std::vector<float>& destination) const;

    /** @returns The smallest input length process() will accept. */
    [[nodiscard]] int getMinimumNumSamples() const noexcept;

    /** @returns The configuration this was built with. */
    [[nodiscard]] const Configuration& getConfiguration() const noexcept { return config; }

private:
    Configuration config;
    std::vector<float> melFilterBank;   // [numMelBins, numBins] row-major
    std::vector<float> analysisWindow;  // periodic Hann, windowSize long

    std::unique_ptr<juce::dsp::FFT> transform;
};

} // namespace rvcara
